---
title: "OY tidycensus"
author: "Amy Shuff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(tidycensus)

```

```{r, results='hide'}

# A Census API key is required.  Obtain one at http://api.census.gov/data/key_signup.html, and then supply the key to the `census_api_key()` function to use it throughout your tidycensus session.

census_api_key("c3d12d20da12dc79099884d8e4a136a9f30a3b39", install = TRUE, overwrite = TRUE)
```


```{r get_pums}

# View variables available for get_pums()
vpums <- pums_variables

# ESR: Employment status recode
#         3 Unemployed
#         6 Not in labor force

# SCHG: Grade level attending
#       	bb  N/A (not attending school)

oy_pums_1yr <- get_pums(
  variables = c("AGEP", "ESR", "SCHG"),
  state = "TX",
  survey = "acs1",
  year = 2022
)
# variables_filter	
# A named list of filters you'd like to return from the PUMS API. For example, passing list(AGE = 25:50, SEX = 1) will return only males aged 25 to 50 in your output dataset.
 
# SERIALNO: a serial number that uniquely identifies households in the sample;
# SPORDER: the order of the person in the household, which when combined with SERIALNO uniquely identifies a person;
# WGTP: the household weight;
# PWGTP: the person weight; (use this for analysis)
# ST: the state FIPS code.

```



```{r get_acs}

# View variables for get_acs
acs20 <- load_variables(2020, "acs5", cache = TRUE)

# B01001_006  Estimate!!Total:!!Male:!!15 to 17 years
# B01001_007  Estimate!!Total:!!Male:!!18 and 19 years
# B01001_008  Estimate!!Total:!!Male:!!20 years
# B01001_009  Estimate!!Total:!!Male:!!21 years
# B01001_010  Estimate!!Total:!!Male:!!22 to 24 years

BIPOC_20_5yr <-  get_acs(geography = "zcta",
                         variables = c(white_und5_male = "B01001A_003", 
                                       white_und5_female = "B01001A_018", 
                                       und5_male = "B01001_003", 
                                       und5_female = "B01001_027"),
                         year = 2020,
                         
                         # geometry = TRUE,
                         # geometry if FALSE (the default), return a regular tibble of ACS data. if TRUE, uses the tigris package to return an sf tibble with simple feature geometry in the 'geometry' column.
                         
                         output = "wide",
                         # output of "tidy" (the default) in which each row represents an enumeration unit-variable combination, or                          "wide" in which each row represents an enumeration unit and the variables are in the columns.
                         
                         survey = "acs5")

#  state = "TX", county = "Harris",

```

```{r get_estimates}

get_estimates()

```
